api_platform:
    title: WR506D - API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    graphql:
        enabled: true
