nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']  # En dev uniquement, restreins en prod
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api':
            allow_origin: ['http://localhost:5173', 'http://localhost:3000']  # le front-end
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
            max_age: 3600
        '^/auth':
            allow_origin: ['http://localhost:5173', 'http://localhost:3000']
            allow_headers: ['Content-Type']
            allow_methods: ['POST', 'OPTIONS']
