nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']
        allow_methods: ['GET','POST','PUT','DELETE','OPTIONS','PATCH']
        allow_headers: ['Content-Type','Authorization']
        expose_headers: ['Link','Content-Range']
        max_age: 3600
    paths:
        '^/': null
