framework:
    rate_limiter:
        # Utilisateurs anonymes
        anonymous_api:
            policy: 'sliding_window'
            limit: 10000  # Augmenté pour le dev (était 10)
            interval: '1 hour'

        # Limiter dynamique pour utilisateurs authentifiés
        # On créera des limiters à la volée avec la limite de chaque user
        authenticated_api:
            policy: 'sliding_window'
            limit: 10000  # Augmenté pour le dev (était 1000)
            interval: '1 hour'
