vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        media_object:
            uri_prefix: /uploads/actors
            upload_destination: '%kernel.project_dir%/public/uploads/actors'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_update: true
            delete_on_remove: true
